### ISSUE TITLE
Version 0.4.0 not published on Maven Central

### ISSUE THREAD

**Issue by gabrielgatu** [muxinc/mux-java#4]
Hi!

The README shows installation instructions for version 0.4.0, but on Maven Central the most recent version is 0.2.3:
https://search.maven.org/artifact/com.mux/mux-sdk-java

Versions missing from Maven Central:
- 0.4.0
- 0.3.0

(Thanks for the library, I really appreciate it)

**Comment by jaredsmith** [comment]
I'm looking into this today.

**Comment by jaredsmith** [comment]
Version 0.4.0 has now been published to Maven Central -- it may take a bit for the search index to catch up.  @gabrielgatu can you please test again when you've got a minute?

**Comment by jaredsmith** [comment]
Version 0.4.0 now shows up in the Maven search as well.  Closing this issue, but feel free to re-open it if you have any other concerns.
